import {describe,it,expect} from 'vitest';
import {initialPieces,legal,beats,applyMove,start,fresh,type Game,type Piece} from '../src/game/engine';
const game=():Game=>start({...fresh('A'),seats:[{id:'a',name:'A',ready:true,rematch:false},{id:'b',name:'B',ready:true,rematch:false}]});
describe('engine',()=>{
 it('sets unique symmetric armies',()=>{const p=initialPieces();expect(p).toHaveLength(18);expect(new Set(p.map(x=>`${x.position.row},${x.position.col}`)).size).toBe(18);expect(p.filter(x=>x.owner===1&&x.type==='rock')).toHaveLength(3)});
 it('allows eight adjacent directions only',()=>{const p:Piece={id:'1',owner:1,type:'rock',position:{row:4,col:4}};for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)expect(legal([p],p,{row:4+dr,col:4+dc})).toBe(dr!==0||dc!==0);expect(legal([p],p,{row:6,col:4})).toBe(false);expect(legal([p],p,{row:4,col:9})).toBe(false)});
 it('enforces capture cycle and friendly blocking',()=>{expect(beats('rock','scissors')).toBe(true);expect(beats('scissors','paper')).toBe(true);expect(beats('paper','rock')).toBe(true);expect(beats('rock','rock')).toBe(false);expect(beats('scissors','rock')).toBe(false);const p:Piece={id:'1',owner:1,type:'rock',position:{row:4,col:4}};expect(legal([p,{...p,id:'2',owner:1,position:{row:4,col:5}}],p,{row:4,col:5})).toBe(false)});
 it('captures and rejects stale, duplicate and wrong-turn moves',()=>{let g=game();g={...g,pieces:[{id:'x',owner:1,type:'rock',position:{row:4,col:4}},{id:'y',owner:2,type:'scissors',position:{row:4,col:5}},{id:'z',owner:2,type:'paper',position:{row:8,col:8}}]};const m={gameId:g.gameId,matchId:g.matchId,moveId:'m',playerId:'a',pieceId:'x',from:{row:4,col:4},to:{row:4,col:5},expectedVersion:g.version};const n=applyMove(g,m);expect(n.pieces.find(x=>x.id==='y')).toBeUndefined();expect(n.turn).toBe(2);expect(applyMove(n,m)).toBe(n);expect(applyMove(g,{...m,playerId:'b'})).toBe(g)});
 it('wins at goal and cannot move afterward',()=>{let g=game();g={...g,pieces:[{id:'x',owner:1,type:'rock',position:{row:7,col:7}},{id:'y',owner:2,type:'paper',position:{row:1,col:1}}]};const m={gameId:g.gameId,matchId:g.matchId,moveId:'m',playerId:'a',pieceId:'x',from:{row:7,col:7},to:{row:8,col:8},expectedVersion:g.version};const n=applyMove(g,m);expect(n.winner).toBe(1);expect(applyMove(n,{...m,moveId:'m2',expectedVersion:n.version})).toBe(n)});
 it('keeps rooms independent',()=>{const a=game(),b=start({...fresh('B'),seats:[{id:'c',name:'C',ready:true,rematch:false},{id:'d',name:'D',ready:true,rematch:false}]});expect(a.gameId).not.toBe(b.gameId);a.pieces.pop();expect(b.pieces).toHaveLength(18)});
});
