import {newId} from './utils/id';
import './style.css';
import {at,legalMoves,icons,kinds,label,initialPieces,type Game,type Pos,type Player} from './game/engine';
import {connect,join,ready,submitMove,agreeRematch,surrender,repairEmptyBoard,type Room} from './multiplayer/room';
const app=document.querySelector<HTMLDivElement>('#app')!;
const code='MAIN';
let room:Room|null=null,selected:string|null=null,error='',name=localStorage.getItem('ott-name')||'',connecting=false;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function home(){app.innerHTML=`<main class="home"><div class="brand">OTT<span>v2</span></div><p class="eyebrow">OẲN TÙ TÌ · CHIẾN THUẬT 9×9</p><h1>Một bàn cờ.<br><em>Vô vàn nước đi.</em></h1><p class="intro">Đưa quân tới góc đối diện hoặc loại hết một loại quân của đối thủ. Mở cùng một đường link với bạn bè để bắt đầu trận đấu.</p><div class="home-card"><label>TÊN CỦA BẠN<input id="name" maxlength="24" placeholder="Nhập tên hiển thị" value="${escape(name)}"></label><button id="enter" class="primary">Vào phòng chơi <span>↗</span></button><p class="error">${escape(error)}</p></div><div class="how"><b>LUẬT CHƠI</b><div><span>✊ thắng ✌️</span><span>✌️ thắng ✋</span><span>✋ thắng ✊</span></div><p>Mỗi lượt đi một ô theo tám hướng. Cùng loại không thể ăn nhau.</p></div></main>`;
 const enter=async()=>{if(connecting)return;const input=app.querySelector<HTMLInputElement>('#name')!;name=input.value.trim().slice(0,24);if(!name){error='Vui lòng nhập tên của bạn';home();return}localStorage.setItem('ott-name',name);if(location.protocol==='file:'){error='Hãy chạy npm run dev và mở địa chỉ http://localhost:5173. Không mở trực tiếp dist/index.html.';home();return}connecting=true;app.innerHTML='<div class="loading">Đang kết nối phòng…</div>';try{room=await connect(code,render);join(room,name);if(room.read().seats[0]?.id===room.identity)repairEmptyBoard(room);error='';render()}catch(e){console.error('Kết nối playhtml thất bại',e);error=`Không kết nối được phòng chung: ${e instanceof Error?e.message:String(e)}. Kiểm tra Internet và mở trang qua npm run dev.`;room=null;home()}finally{connecting=false}};
 app.querySelector('#enter')!.addEventListener('click',()=>void enter());
}
function render(){if(!room){home();return}const g=room.read(),me=g.seats.findIndex(s=>s?.id===room!.identity),online=room.online();const active=me>=0&&g.status==='PLAYING'&&g.turn===me+1&&g.seats.every(s=>s&&online.has(s.id));const displayedPieces=g.status==='WAITING'?initialPieces():g.pieces;const piece=g.pieces.find(p=>p.id===selected&&p.owner===me+1);const moves=active&&piece?legalMoves(g.pieces,piece):[];
 const player=(n:Player)=>{const s=g.seats[n-1],counts=kinds.map(k=>`<span>${icons[k]} ${displayedPieces.filter(p=>p.owner===n&&p.type===k).length}</span>`).join('');return `<div class="player p${n} ${g.turn===n&&g.status==='PLAYING'?'turn':''}"><div class="avatar">${n===1?'01':'02'}</div><div><small>PLAYER ${n} ${s?.id===room!.identity?'· BẠN':''}</small><strong>${escape(s?.name||'Đang chờ người chơi')}</strong>${g.status==='WAITING'&&s?`<small>${s.ready?'Đã sẵn sàng':'Chưa sẵn sàng'}</small>`:''}<div class="pieces">${counts}</div></div><span class="dot ${s&&online.has(s.id)?'on':''}"></span></div>`};
 let board='<div class="coordinates"><span></span>'+[...'abcdefghi'].map(c=>`<span>${c}</span>`).join('')+'</div><div class="board">';for(let r=0;r<9;r++){board+=`<span class="row-num">${r+1}</span>`;for(let c=0;c<9;c++){const pos={row:r,col:c},p=at(displayedPieces,pos),target=moves.some(m=>m.row===r&&m.col===c),goal=r===0&&c===0||r===8&&c===8;board+=`<button class="cell ${(r+c)%2?'dark':'light'} ${p?'occupied':''} ${p?.owner===1?'blue':p?.owner===2?'orange':''} ${p?.id===selected?'selected':''} ${target?(p?'capture':'possible'):''} ${goal?'goal':''}" data-r="${r}" data-c="${c}" aria-label="${label(pos)} ${p?icons[p.type]:''}">${goal?'<span class="goal-mark">◆</span>':''}${p?`<span class="token">${icons[p.type]}</span>`:''}</button>`}}board+='</div>';
 const status=g.status==='WAITING'?'CHỜ BẮT ĐẦU':g.status==='FINISHED'?'TRẬN ĐẤU KẾT THÚC':`LƯỢT PLAYER ${g.turn}`;
 app.innerHTML=`<div class="shell"><header><div class="brand small">OTT<span>v2</span></div><div class="room-code">PHÒNG CHUNG</div><div class="connection"><i></i> Đã kết nối</div><button id="copy">Sao chép link ↗</button></header><main class="layout"><section class="game-area"><div class="game-title"><div><p class="eyebrow">TRẬN ${g.match} · ${g.history.length} NƯỚC ĐI</p><h1>${status}</h1></div><span class="badge">${me<0?'KHÁN GIẢ':`PLAYER ${me+1}`}</span></div>${player(2)}<div class="board-wrap">${board}</div>${player(1)}<p class="hint">${g.status==='PLAYING'?(active?'Chọn quân của bạn, sau đó chọn ô được đánh dấu.':'Đang chờ lượt hoặc đối thủ kết nối lại.'):'Đây là đội hình xem trước. Cần hai trình duyệt hoặc hai browser profile khác nhau; cả hai người bấm Sẵn sàng để bắt đầu.'}</p></section><aside><div class="side-card"><p class="eyebrow">PHÒNG CHUNG</p><p>Chia sẻ đường link trang này để mời bạn bè.</p>${g.status==='WAITING'&&me>=0?`<button id="ready" class="primary">${g.seats[me]?.ready?'Hủy sẵn sàng':'Tôi đã sẵn sàng'}</button>`:''}${g.status==='PLAYING'&&me>=0&&g.pieces.length===0?'<button id="repair" class="primary">Bắt đầu lại ván</button>':''}${g.status==='PLAYING'&&me>=0?'<button id="surrender" class="danger">Đầu hàng</button>':''}${g.status==='FINISHED'&&me>=0?`<button id="rematch" class="primary">${g.seats[me]?.rematch?'Đang chờ đối thủ…':'Đề nghị chơi lại'}</button>`:''}</div><div class="side-card"><p class="eyebrow">CÁCH CHƠI</p><p>Đi một ô theo tám hướng. ✊ ăn ✌️ · ✌️ ăn ✋ · ✋ ăn ✊. Loại hết một loại quân đối phương hoặc tới góc đích để thắng.</p></div><div class="side-card history"><p class="eyebrow">LỊCH SỬ NƯỚC ĐI</p>${g.history.length?g.history.slice().reverse().map((h,i)=>`<div><span>${g.history.length-i}.</span> ${escape(h.text)}</div>`).join(''):'<p>Chưa có nước đi nào.</p>'}</div></aside></main>${g.status==='FINISHED'?`<div class="modal-back"><div class="modal"><p class="eyebrow">KẾT QUẢ TRẬN ${g.match}</p><div class="trophy">${g.winner?'✦':'◇'}</div><h2>${g.winner?`${escape(g.seats[g.winner-1]?.name||'Người chơi')} chiến thắng!`:'Trận đấu hòa'}</h2><p>${escape(g.reason)}</p><p>${g.history.length} nước đi</p>${me>=0?'<button id="modal-rematch" class="primary">Chơi lại</button>':''}<button id="home">Về trang chủ</button></div></div>`:''}</div>`;
 app.querySelectorAll<HTMLButtonElement>('.cell').forEach(b=>b.onclick=()=>clickCell(g,{row:Number(b.dataset.r),col:Number(b.dataset.c)},active));
 app.querySelector('#copy')?.addEventListener('click',()=>void navigator.clipboard.writeText(location.href));app.querySelector('#ready')?.addEventListener('click',()=>ready(room!));app.querySelector('#rematch')?.addEventListener('click',()=>agreeRematch(room!));app.querySelector('#modal-rematch')?.addEventListener('click',()=>agreeRematch(room!));app.querySelector('#surrender')?.addEventListener('click',()=>surrender(room!));app.querySelector('#repair')?.addEventListener('click',()=>repairEmptyBoard(room!));app.querySelector('#home')?.addEventListener('click',()=>{history.replaceState(null,'',location.pathname);location.reload()});
}
function clickCell(g:Game,pos:Pos,active:boolean){if(!active||!room)return;const me=g.seats.findIndex(s=>s?.id===room!.identity)+1,p=at(g.pieces,pos);if(p?.owner===me){selected=p.id;render();return}const chosen=g.pieces.find(p=>p.id===selected);if(chosen&&legalMoves(g.pieces,chosen).some(x=>x.row===pos.row&&x.col===pos.col)){submitMove(room,{gameId:g.gameId,matchId:g.matchId,moveId:newId(),playerId:room.identity,pieceId:chosen.id,from:chosen.position,to:pos,expectedVersion:g.version});selected=null;render()}}
home();
