import './style.css';
import {newId} from './utils/id';
import {at,legalMoves,icons,kinds,label,initialPieces,type Game,type Pos,type Player} from './game/engine';
import {connectLobby,createRoom,joinRoom,leave,ready,submitMove,agreeRematch,surrender,type Lobby,type Room} from './multiplayer/room';

const app=document.querySelector<HTMLDivElement>('#app')!;
let lobby:Lobby|null=null,room:Room|null=null,selected:string|null=null;
let name=localStorage.getItem('ott-name')||'',error='';
let invitation=new URLSearchParams(location.search).get('room')?.toUpperCase()||'';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const copy=(s:string)=>void navigator.clipboard.writeText(s);

function render(){if(!lobby){app.innerHTML='<div class="loading">Đang kết nối danh sách phòng…</div>';return}if(room&&!room.listed()){room.close();room=null;error='Phòng đã đóng vì trận kết thúc và không còn đủ hai người chơi.';history.replaceState(null,'',location.pathname)}if(room)renderGame();else renderHome()}
function getName(){const input=app.querySelector<HTMLInputElement>('#name');const value=input?.value.trim().slice(0,24)||'';if(!value){error='Vui lòng nhập tên của bạn';renderHome();return null}name=value;localStorage.setItem('ott-name',name);return name}
function enter(code?:string){if(!lobby)return;const playerName=getName();if(!playerName)return;try{room=code?joinRoom(lobby,code,playerName,render):createRoom(lobby,playerName,render);selected=null;error='';history.replaceState(null,'',`?room=${room.code}`);render()}catch(e){error=e instanceof Error?e.message:String(e);renderHome()}}
function renderHome(){if(!lobby)return;const rows=lobby.list().map(m=>{const count=Number(!!m.player1)+Number(!!m.player2);return `<div class="room-row"><div><b>${escape(m.code)}</b><small>${escape(m.name1||'Trống')} · ${escape(m.name2||'Trống')} · ${count}/2 · ${m.status==='WAITING'?'Đang chờ':m.status==='PLAYING'?'Đang chơi':'Đã xong'}</small></div><button data-room="${escape(m.code)}">Vào phòng</button></div>`}).join('');
 app.innerHTML=`<main class="home"><div class="brand">OTT<span>v2</span></div><p class="eyebrow">OẲN TÙ TÌ · CHIẾN THUẬT 9×9</p><h1>Chọn phòng.<br><em>Bắt đầu ván đấu.</em></h1><p class="intro">Tạo phòng mới, gửi mã cho bạn bè hoặc tham gia một phòng đang có.</p><div class="home-card"><label>TÊN CỦA BẠN<input id="name" maxlength="24" placeholder="Nhập tên hiển thị" value="${escape(name)}"></label><button id="create" class="primary">Tạo phòng mới <span>↗</span></button><div class="divider">HOẶC THAM GIA BẰNG MÃ</div><div class="join-row"><input id="code" maxlength="12" placeholder="Mã phòng" value="${escape(invitation)}"><button id="join">Tham gia</button></div><p class="error">${escape(error)}</p></div><section class="room-list"><p class="eyebrow">PHÒNG HIỆN CÓ · ${lobby.list().length}</p>${rows||'<p class="empty-rooms">Chưa có phòng nào. Hãy tạo phòng đầu tiên.</p>'}</section><div class="how"><b>LUẬT CHƠI</b><div><span>✊ thắng ✌️</span><span>✌️ thắng ✋</span><span>✋ thắng ✊</span></div><p>Mỗi lượt đi một ô theo tám hướng. Cùng loại không thể ăn nhau.</p></div></main>`;
 app.querySelector('#create')!.addEventListener('click',()=>enter());
 app.querySelector('#join')!.addEventListener('click',()=>{const code=app.querySelector<HTMLInputElement>('#code')!.value.trim().toUpperCase();if(!code){error='Vui lòng nhập mã phòng';renderHome();return}enter(code)});
 app.querySelectorAll<HTMLButtonElement>('[data-room]').forEach(b=>b.addEventListener('click',()=>enter(b.dataset.room)));
}
function renderGame(){if(!room)return;const g=room.read(),me=g.seats.findIndex(s=>s?.id===room!.identity),online=room.online();const active=me>=0&&g.status==='PLAYING'&&g.turn===me+1;const displayed=g.status==='WAITING'?initialPieces():g.pieces;const piece=g.pieces.find(p=>p.id===selected&&p.owner===me+1);const moves=active&&piece?legalMoves(g.pieces,piece):[];
 const player=(n:Player)=>{const s=g.seats[n-1],counts=kinds.map(k=>`<span>${icons[k]} ${displayed.filter(p=>p.owner===n&&p.type===k).length}</span>`).join('');return `<div class="player p${n} ${g.turn===n&&g.status==='PLAYING'?'turn':''}"><div class="avatar">${n===1?'01':'02'}</div><div><small>PLAYER ${n} ${s?.id===room!.identity?'· BẠN':''}</small><strong>${escape(s?.name||'Đang chờ người chơi')}</strong>${g.status==='WAITING'&&s?`<small>${s.ready?'Đã sẵn sàng':'Chưa sẵn sàng'}</small>`:''}<div class="pieces">${counts}</div></div><span class="dot ${s&&online.has(s.id)?'on':''}"></span></div>`};
 let board='<div class="coordinates"><span></span>'+[...'abcdefghi'].map(c=>`<span>${c}</span>`).join('')+'</div><div class="board">';for(let r=0;r<9;r++){board+=`<span class="row-num">${r+1}</span>`;for(let c=0;c<9;c++){const pos={row:r,col:c},p=at(displayed,pos),target=moves.some(m=>m.row===r&&m.col===c),goal=r===0&&c===0||r===8&&c===8,recent=g.lastMove&&((g.lastMove.from.row===r&&g.lastMove.from.col===c)||(g.lastMove.to.row===r&&g.lastMove.to.col===c));board+=`<button class="cell ${(r+c)%2?'dark':'light'} ${p?'occupied':''} ${p?.owner===1?'blue':p?.owner===2?'orange':''} ${p?.id===selected?'selected':''} ${target?(p?'capture':'possible'):''} ${goal?'goal':''} ${recent?'recent':''}" data-r="${r}" data-c="${c}" aria-label="${label(pos)} ${p?icons[p.type]:''}">${goal?'<span class="goal-mark">◆</span>':''}${p?`<span class="token">${icons[p.type]}</span>`:''}</button>`}}board+='</div>';
 const status=g.status==='WAITING'?'CHỜ BẮT ĐẦU':g.status==='FINISHED'?'TRẬN ĐẤU KẾT THÚC':`LƯỢT PLAYER ${g.turn}`;
 app.innerHTML=`<div class="shell"><header><div class="brand small">OTT<span>v2</span></div><div class="room-code">PHÒNG <b>${escape(room.code)}</b></div><div class="connection"><i></i> Đã kết nối</div><button id="copy-link">Sao chép link ↗</button></header><main class="layout"><section class="game-area"><div class="game-title"><div><p class="eyebrow">TRẬN ${g.match} · ${g.history.length} NƯỚC ĐI</p><h1>${status}</h1></div><span class="badge">${me<0?'KHÁN GIẢ':`PLAYER ${me+1}`}</span></div>${player(2)}<div class="board-wrap">${board}</div>${player(1)}<p class="hint">${g.status==='PLAYING'?(me<0?'Bạn đang xem với vai trò khán giả.':active?'Đến lượt bạn: chọn quân rồi chọn ô được đánh dấu.':'Đang chờ Player '+g.turn+' đi quân.'):g.status==='FINISHED'?'Trận đã kết thúc. Phòng sẽ đóng nếu còn dưới hai người chơi online.':'Đây là đội hình xem trước. Cả hai người chơi cần bấm Sẵn sàng.'}</p></section><aside><div class="side-card"><p class="eyebrow">MÃ PHÒNG</p><div class="code-large">${escape(room.code)}</div><button id="copy-code">Sao chép mã</button>${g.status==='WAITING'&&me>=0?`<button id="ready" class="primary">${g.seats[me]?.ready?'Hủy sẵn sàng':'Tôi đã sẵn sàng'}</button>`:''}${g.status==='PLAYING'&&me>=0?'<button id="surrender" class="danger">Đầu hàng</button>':''}${g.status==='FINISHED'&&me>=0?`<button id="rematch" class="primary">${g.seats[me]?.rematch?'Đang chờ đối thủ…':'Chơi lại'}</button>`:''}<button id="leave">Rời phòng</button></div><div class="side-card"><p class="eyebrow">CÁCH CHƠI</p><p>Đi một ô theo tám hướng. ✊ ăn ✌️ · ✌️ ăn ✋ · ✋ ăn ✊. Loại hết một loại quân đối phương hoặc tới góc đích để thắng.</p></div><div class="side-card history"><p class="eyebrow">LỊCH SỬ NƯỚC ĐI</p>${g.history.length?g.history.slice().reverse().map((h,i)=>`<div><span>${g.history.length-i}.</span> ${escape(h.text)}</div>`).join(''):'<p>Chưa có nước đi nào.</p>'}</div></aside></main>${g.status==='FINISHED'&&me>=0?`<div class="modal-back"><div class="modal"><p class="eyebrow">KẾT QUẢ TRẬN ${g.match}</p><div class="trophy">${g.winner?'✦':'◇'}</div><h2>${g.winner?`${escape(g.seats[g.winner-1]?.name||'Người chơi')} chiến thắng!`:'Trận đấu hòa'}</h2><p>${escape(g.reason)}</p><p>${g.history.length} nước đi</p><button id="modal-rematch" class="primary">Chơi lại</button><button id="home">Về danh sách phòng</button></div></div>`:''}</div>`;
 app.querySelectorAll<HTMLButtonElement>('.cell').forEach(b=>b.onclick=()=>clickCell(g,{row:Number(b.dataset.r),col:Number(b.dataset.c)},active));
 app.querySelector('#copy-link')?.addEventListener('click',()=>copy(location.href));app.querySelector('#copy-code')?.addEventListener('click',()=>copy(room!.code));app.querySelector('#ready')?.addEventListener('click',()=>ready(room!));app.querySelector('#rematch')?.addEventListener('click',()=>agreeRematch(room!));app.querySelector('#modal-rematch')?.addEventListener('click',()=>agreeRematch(room!));app.querySelector('#surrender')?.addEventListener('click',()=>surrender(room!));app.querySelector('#leave')?.addEventListener('click',leaveRoom);app.querySelector('#home')?.addEventListener('click',leaveRoom);
}
function leaveRoom(){if(room){leave(room);room.close();room=null}selected=null;invitation='';history.replaceState(null,'',location.pathname);render()}
function clickCell(g:Game,pos:Pos,active:boolean){if(!active||!room)return;const me=g.seats.findIndex(s=>s?.id===room!.identity)+1,p=at(g.pieces,pos);if(p?.owner===me){selected=p.id;render();return}const chosen=g.pieces.find(p=>p.id===selected);if(chosen&&legalMoves(g.pieces,chosen).some(x=>x.row===pos.row&&x.col===pos.col)){submitMove(room,{gameId:g.gameId,matchId:g.matchId,moveId:newId(),playerId:room.identity,pieceId:chosen.id,from:chosen.position,to:pos,expectedVersion:g.version});selected=null;render()}}

if(location.protocol==='file:'){app.innerHTML='<div class="loading">Hãy chạy npm run dev và mở địa chỉ HTTP do Vite cung cấp.</div>'}else{render();connectLobby(render).then(value=>{lobby=value;render()}).catch(e=>{app.innerHTML=`<div class="loading">Không kết nối được danh sách phòng: ${escape(String(e))}</div>`})}
